---

- name: "Before Installation | Set fluentXvars"
  blockinfile:
    dest: /etc/environment
    backup: no
    insertafter: EOF
    content: |
      '{{ fluentd_certpass }}'
      '{{ fleuntd_sharedkey }}'
  register: fluentvars

- name: "Before Installation | source /etc/environment"
  shell: 
     "source /etc/environment"
  register: sourceenvironment
