---

- name: "Before Installation | Set fluentXvars"
  blockinfile:
    dest: /etc/sysconfig/fluent-bit
    backup: no
    insertafter: EOF
    content: |
      {{ fluentd_certpass }}
      {{ fluentd_sharedkey }}
  register: fluentvars

- name: "Before Installation | source /etc/sysconfig/fluent-bit"
  shell: 
     "source /etc/sysconfig/fluent-bit"
  register: sourcefbsysconfig