---

- name: Install Ubuntu-20 | Add Fluentbit apt-key
  apt_key:
    url: '{{ fluentbit_apt_key }}'
    state: present

- name: Install Ubuntu-20 | Add Fluentbit repository
  apt_repository:
    repo: '{{ fluentbit_apt20_repo }}'
    state: present
    filename: fluent-bit
    update_cache: true
