---

- name: start fluentbit service
  service:
    name: fluent-bit
    state: started
  become: true

- name: stop fluentbit service
  service:
    name: fluent-bit
    state: stopped
  become: true

- name: restart fluentbit service
  service:
    name: fluent-bit
    state: restarted
  become: true
